# BetterSuicide, made by Cherryh4ck
# This is the configuration file for the plugin.

# --- Variables ---

# Automatically redirect /kill to /minecraft:kill for OPs?
# By default, this is true.
redirect-kill-for-ops: true

# Use permissions to use /kill and /suicide?
# You probably want this set to false if you want everybody to have access to those commands.
# Permission - bettersuicide.suicide
use-permission: false

# --- Messages ---
# Supports mini-message formatting!
no-permissions: "<red>You do not have the permissions to do this."