# BetterSuicide, made by Cherryh4ck
# This is the configuration file for the plugin.

# --- Variables ---

# Plugin prefix
plugin-prefix: "<gold><b>[BetterSuicide]<reset>"

# Automatically redirect /kill to /minecraft:kill for OPs?
# By default, this is true.
redirect-kill-for-ops: true

# Use permissions to use /kill and /suicide?
# You probably want this set to false if you want everybody to have access to those commands.
# Permission - bettersuicide.suicide
use-permission: false

# Should /kill & /suicide have a cooldown delay?
# Permission to bypass - bettersuicide.bypass
enable-cooldown: false

# If so, how much in seconds?
cooldown-timer: 4

# Should the plugin display an error when the player is on cooldown?
enable-cooldown-message: false

# --- Messages ---
# Supports mini-message formatting!
no-permissions: "<red>You do not have the permissions to do this."
cooldown-active: "<red>You are on a cooldown."